// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sluzesergikpahlxwxya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsdXplc2VyZ2lrcGFobHh3eHlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3Mjk2ODksImV4cCI6MjA3OTMwNTY4OX0.KlZLrr5SrNv-DB1T-MXyhIJ6RXAApa45ZsK2qufU9Do";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});